<?php if ($data): ?>
    <?php foreach ($data as $item): ?>
        <div class="col-md-3 <?= $item->id ?>" id="<?= $item->id ?>">
            <!-- Profile Image -->
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <img class="profile-user-img img-responsive img-circle" src="<?= base_url($item->cover) ?>" alt="User profile picture">

                    <h3 class="profile-username text-center"><?= $item->first_name; ?> <?= $item->first_name; ?></h3>

                    <p class="text-muted text-center"><?= $item->email; ?></p>

                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item">
                            <b>Roles</b> <a class="pull-right">Admin</a>
                        </li>
                    </ul>
                    <a href="<?=
                    $this->router->pathFor('usuarios.edit', [
                        'id' => $item->id
                    ])
                    ?>" class="btn btn-primary  btn-flat"><i class="fa fa-pencil"></i></a>
                    <a href="<?=
                    $this->router->pathFor('usuarios.delete', [
                        'id' => $item->id
                    ])
                    ?>" class="btn btn-danger btn-flat action-delete"><i class="fa fa-trash-o"></i></a>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
            <!-- About Me Box -->
            <!-- /.box -->
        </div>
    <?php endforeach; ?>
<?php endif; ?>