
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= $this->baseUrl ?>/<?= $auth->user()->cover ?>" class="img-circle" alt=" <?= sprintf("%s %s", $auth->user()->first_name, $auth->user()->last_name); ?>">
            </div>
            <div class="pull-left info">
                <p> <?= sprintf("%s %s", $auth->user()->first_name, $auth->user()->last_name); ?></p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li ><a href="<?= base_url('admin') ?>"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
            <!-- Optionally, you can add icons to the links -->        
            <li  class="treeview <?= $this->active->active($this->router->pathFor('clients')); ?>">
                <a href="#"><i class="fa fa-users"></i> <span>Clientes</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?= $this->router->pathFor('clients') ?>">Listar Clientes</a></li>
                    <li><a href="<?= $this->router->pathFor('clients.create') ?>">Cadastrar Clientes</a></li>
                </ul>
            </li>
            <li  class="treeview <?= $this->active->active($this->router->pathFor('products')); ?>
            <?= $this->active->active($this->router->pathFor('categories')); ?>
                 <?= $this->active->active($this->router->pathFor('brands')); ?>">
                <a href="#"><i class="fa fa-cubes"></i> <span>Produtos</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?= base_url('admin/products') ?>">Listar Produtos</a></li>
                    <li><a href="<?= $this->router->pathFor('categories') ?>">Listar Categorias</a></li>
                    <li><a href="<?= $this->router->pathFor('brands') ?>">Listar Brands</a></li>
                    <li><a href="<?= base_url('admin/products/create') ?>">Cadastrar Produtos</a></li>
                </ul>
            </li>
            <li class="treeview <?= $this->active->active($this->router->pathFor('usuarios')); ?>">
                <a href="#"><i class="fa fa-user"></i> <span>Usuarios</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="<?= base_url('admin/usuarios') ?>">Listar Usuarios</a></li>
                    <li><a href="<?= base_url('admin/usuarios/create') ?>">Cadastrar</a></li>
                </ul>
            </li>
            <li><a href="<?= base_url('admin/logout') ?>"><i class="fa fa-sign-out"></i> <span>Sair Do Sistema</span></a></li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>