<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Administração
            <small>Lista De Empresas</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="<?= $this->router->pathFor('admin') ?>"><i class="fa fa-dashboard"></i> DashBoard</a></li>
            <li><a href="<?= $this->router->pathFor('companys') ?>"><i class="fa fa-dashboard"></i> Empresas</a></li>
            <li class="active">Here</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-3">
                <?=
                $this->partials('upload', [
                    'id' => $data->id,
                    'name' => $data->name,
                    'cover' => $data->cover,
                    'route' => $route
                ])
                ?>                
            </div>
            <div class="col-md-9">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#dados" data-toggle="tab" aria-expanded="true">Dados Do Usuario</a></li>
                        <li class=""><a href="#description" data-toggle="tab" aria-expanded="false">Descrição</a></li>
                        <li><a href="#cat_brand" data-toggle="tab">Categoria & Marca</a></li>
                        <li><a href="#caracteristicas" data-toggle="tab">Caracteristicas</a></li>
                        <li><a href="#fiscal" data-toggle="tab">Fiscal</a></li>
                        <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="dados">
                            <form role="form" action="<?= $this->getAttribute('router')->pathFor('companys.store') ?>" class="ajaxForm">
                                <input type="hidden" name="id" value="<?= $data->id ?>">
                                <input type="hidden" name="parent" value="<?= $data->parent ?>">
                                <?= $this->partials('text', ['name' => 'name', 'label' => 'Name', 'value' => $data->name]) ?>   
                                <?= $this->partials('text', ['name' => 'fantasia', 'label' => 'Name Fantasy', 'value' => $data->fantasia]) ?>   
                                <?= $this->partials('text', ['name' => 'email', 'label' => 'E-Mail', 'value' => $data->email]) ?>   
                                <?= $this->partials('text', ['name' => 'document ', 'label' => 'Cpf/Cnpj', 'value' => $data->document ]) ?>   
                                <?= $this->partials('text', ['name' => 'phone', 'label' => 'Phone', 'value' => $data->phone]) ?>   
                                <?= $this->partials('text', ['name' => 'cel', 'label' => 'Celular', 'value' => $data->cel]) ?>   
                                <hr><legend>Address</legend>
                                <?= $this->partials('text', ['name' => 'zipcode ', 'label' => 'ZipCode', 'value' => $data->zipcode ]) ?>   
                                <?= $this->partials('text', ['name' => 'street', 'label' => 'Street', 'value' => $data->street]) ?>   
                                <?= $this->partials('text', ['name' => 'district ', 'label' => 'District ', 'value' => $data->district ]) ?>   
                                <?= $this->partials('text', ['name' => 'number', 'label' => 'Number', 'value' => $data->number]) ?>   
                                <?= $this->partials('text', ['name' => 'complement', 'label' => 'Complement', 'value' => $data->complement]) ?>   
                                <?= $this->partials('text', ['name' => 'city', 'label' => 'City', 'value' => $data->city]) ?>   
                                <?= $this->partials('text', ['name' => 'state', 'label' => 'State', 'value' => $data->state]) ?>   
                                <?= $this->partials('text', ['name' => 'country', 'label' => 'Country', 'value' => $data->country]) ?>   
                                <?= $this->partials('text', ['name' => 'alias', 'label' => 'Alias (Slug)', 'value' => $data->alias]) ?>   
                                <?= $this->getAttribute('csrf'); ?>
                                <!-- /.box-body -->

                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="description">
                            <form role="form" action="" class="ajaxForm">

                                description

                            </form>
                        </div>
                        <div class="tab-pane" id="cat_brand">
                            <form role="form" action="" class="ajaxForm">

                                cat_brand

                            </form>
                        </div>
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="caracteristicas">

                            caracteristicas

                        </div>
                        <div class="tab-pane" id="fiscal">

                            Fiscal

                        </div>
                        <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                </div>

            </div>

        </div>

</div>
<!-- /.box -->
</section>
</div>
<!-- /.col -->