<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Administração
            <small>Lista De Usuarios</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
            <li class="active">Here</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-3">
                <form id="ajaxForm-upload" action="<?= $this->getAttribute('router')->pathFor('products.upload') ?>" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="id" value="<?= $data->id ?>">
                    <div class="box box-primary">
                        <div class="box-body box-profile">
                            <img data-cover="<?= base_url($data->cover) ?>" id="attachment" class="profile-user-img img-responsive img-circle" src="<?= base_url($data->cover) ?>" alt="User profile picture">
                            <h3 class="profile-username text-center"><?= $data->name ?></h3>
                            <p class="text-muted text-center"><?= $data->email ?></p>
                            <?= $this->getAttribute('csrf'); ?>
                            <div class="form-group">
                                <div class="btn btn-default btn-file btn-block">
                                    <i class="fa fa-paperclip"></i> Attachment
                                    <input  type="file" name="attachment">
                                </div>
                                <p class="help-block">Max. 32MB</p>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                </form>
            </div>
            <div class="col-md-9">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#dados" data-toggle="tab" aria-expanded="true">Dados Do Usuario</a></li>
                        <li class=""><a href="#description" data-toggle="tab" aria-expanded="false">Descrição</a></li>
                        <li><a href="#cat_brand" data-toggle="tab">Categoria & Marca</a></li>
                        <li><a href="#caracteristicas" data-toggle="tab">Caracteristicas</a></li>
                        <li><a href="#fiscal" data-toggle="tab">Fiscal</a></li>
                        <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="dados">
                            <form role="form" action="<?= $this->getAttribute('router')->pathFor('products.store') ?>" class="ajaxForm">
                                <input type="hidden" name="id" value="<?= $data->id ?>">
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input class="form-control" id="email" name="name" placeholder="Name" type="text" value="<?= $data->name ?>">
                                </div>
                                <div class="form-group">
                                    <label for="code">Code</label>
                                    <input class="form-control" id="email" name="code" placeholder="Code Barra" type="text" value="<?= $data->code ?>">
                                </div>
                                <div class="form-group">
                                    <label for="prview">Preview</label>
                                    <input class="form-control" id="email" name="preview" placeholder="Preview" type="text" value="<?= $data->preview ?>">
                                </div>
                                <div class="form-group">
                                    <label for="costs">Costs</label>
                                    <input class="form-control real" id="costs" name="costs" placeholder="Costs" type="text" value="<?= $data->costs ?>">
                                </div>
                                <div class="form-group">
                                    <label for="marge">Marge</label>
                                    <input class="form-control real" id="marge" name="marge" placeholder="Marge" type="text" value="<?= $data->marge ?>">
                                </div>
                                <div class="form-group">
                                    <label for="price">Price</label>
                                    <input class="form-control real" readonly id="price" name="price" placeholder="Price" type="text" value="<?= $data->price ?>">
                                </div>
                                <div class="form-group">
                                    <label for="alias">Alias (Slug)</label>
                                    <input class="form-control" readonly id="alias" name="alias" placeholder="Alias" type="text" value="<?= $data->alias ?>">
                                </div>
                                <?= $this->getAttribute('csrf'); ?>
                                <!-- /.box-body -->

                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="description">
                            <form role="form" action="" class="ajaxForm">
                               
                                description
                                
                            </form>
                        </div>
                         <div class="tab-pane" id="cat_brand">
                            <form role="form" action="" class="ajaxForm">
                               
                                cat_brand
                                
                            </form>
                        </div>
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="caracteristicas">

                            caracteristicas
                            
                        </div>
                         <div class="tab-pane" id="fiscal">

                            Fiscal
                            
                        </div>
                        <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                </div>

            </div>

        </div>

</div>
<!-- /.box -->
</section>
</div>
<!-- /.col -->