<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Painel Do Cliente
            <small>Lista De Marcas</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="<?= $this->router->pathFor('admin') ?>"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href="<?= $this->router->pathFor('products') ?>"><i class="fa fa-cubes"></i> Produtos</a></li>
            <li class="active">Marcas</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">

        <section class="content">
            <div class="row">
                <?= $this->alert->alerts(); ?>
                <?=
                $this->partials('sub-sidebar', [
                    'model' => $model,
                    'route' => $route
                ])
                ?>
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Marcas</h3>                                           
                            <!-- /.box-tools -->
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body no-padding">
                            <div class="table-responsive mailbox-messages">
                                <table id="datTable" class="table table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>Nome</th>
                                            <th>Status</th>
                                            <th>Ações</th>

                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Nome</th>
                                            <th>Status</th>
                                            <th>Ações</th>

                                        </tr>
                                    </tfoot>
                                </table>
                                <!-- /.table -->
                            </div>
                            <!-- /.mail-box-messages -->
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /. box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>

    </section>
    <!-- /.content -->
</div>
<script>
    //var selectURL = '/api/busca';
    var options = {
        "ajax": "/api/brands"
    };
</script>